#!/usr/bin/python

import os
import vagrant
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Get SSH Vagrant SSH information")
    parser.add_argument("--vm", dest="vm", required=False, default=None)
    parser.add_argument("--ip", dest="ip", required=False, default=None, action='store_true')
    parser.add_argument("--port", dest="port", required=False, default=None, action='store_true')

    args = parser.parse_args()

    try:
        if args.vm is None:
            vmpath = os.getcwd()
        else:
            vmpath = args.vm
        vm = vagrant.Vagrant(vmpath)

        if args.ip:
            print("%s@%s" % (vm.user(), vm.hostname()))
        if args.port:
            print("%s" % vm.port())
        if args.port and args.ip:
            print("%s" % vm.user_hostname_port())
        if not args.ip and not args.port:
            print(parser.usage)

    except Exception as ex:
        print("Oops... %s" % ex)
